#!/bin/bash
# Install applications that are not directly present in the main software repositories
# Fetch the source from the upstream repo and download it on the user machine
set -euo pipefail
IFS=$'\n\t'

# Change to temporary directory
cd $(mktemp -d)

echo 'Installing applications...'
echo 'All jobs done!'
echo 'Please reboot your computer to complete the installation.'
exit 0
